### ISSUE TITLE
If user clicks the route selection background, it's CSS class is set to "active-route"

### ISSUE THREAD

**Issue by Niklas-Seppala** [Niklas-Seppala/barspotting#13]
![image](https://user-images.githubusercontent.com/66251857/94990843-a3194c00-0587-11eb-8c73-603c57c6c2b9.png)
![image](https://user-images.githubusercontent.com/66251857/94990859-b88e7600-0587-11eb-9edb-7c0aa445ae71.png)

**Comment by Niklas-Seppala** [comment]
Also, when the user selects another location, the route section still has the `active-route` class.
![image](https://user-images.githubusercontent.com/66251857/94990924-2b97ec80-0588-11eb-8a1c-93f3d1d85fe0.png)

**Comment by Paattis** [comment]
heitin pull requestia korjauksesta
