### ISSUE TITLE
Move back button to right-top corner

### ISSUE THREAD

**Issue by Niklas-Seppala** [Niklas-Seppala/barspotting#17]
![image](https://user-images.githubusercontent.com/66251857/94992464-df9e7500-0592-11eb-9a21-9b91131b0a2f.png)

**Comment by hjvsantos** [comment]
I'm interested to do this, Can you assign this

**Comment by Paattis** [comment]
@hjvsantos Sorry, this is a school project so we cannot let other people contribute code right now. However, you are free to fork this project and make your own version relevant to your own local area.
