### ISSUE TITLE
Unnecessary scrollbar when there is nothing to scroll

### ISSUE THREAD

**Issue by Niklas-Seppala** [Niklas-Seppala/barspotting#7]
![image](https://user-images.githubusercontent.com/66251857/94989464-b0313d80-057d-11eb-86bf-89d56fb20031.png)

**Comment by lucasTovo** [comment]
como deve ser executado o seu código?

**Comment by Paattis** [comment]
> 
> 
> how should your code be executed?
You host this by putting the `src` directory's contents into the relevant apache/nginx directory for hosting files on your server. Please refer to your apache/nginx documentation on where this directory is. 

Please note that the bars are taken from the Helsinki city open API, so unless you live in Helsinki the bars are not going to be relevant for you. Also the public transport API we use only covers Helsinki, Finland and the cities bordering it (Vantaa, Espoo, Kauniainen, Kerava etc.)
