### ISSUE TITLE
"Back"-button doesn't work.

### ISSUE THREAD

**Issue by Niklas-Seppala** [Niklas-Seppala/barspotting#8]
## Before
![image](https://user-images.githubusercontent.com/66251857/94989696-59c4fe80-057f-11eb-853d-bcca578fa725.png)

## After
![image](https://user-images.githubusercontent.com/66251857/94989702-65182a00-057f-11eb-857a-2c000dca1416.png)

**Comment by HeitorSaldanha** [comment]
What is the expected behavior exactly? To close the overlay?

**Comment by Paattis** [comment]
made a pull request with the fix
